### ISSUE TITLE
Error After latest patch

### ISSUE THREAD

**Issue by ozdeadmeat** [Dzsek/vs-code-dsc-injector#2]
2023-07-26 05:56:44.448 INFO    Lua-Injector (Main): [string "Scripts\JSON.lua"]:525: [string "Scripts\JSON.lua"]:240: can't parse JSON at char 1 of: default

I am loading another JSON.lua script into my mission under the variable name JSON, is that going to be an issue? The file is not the same path as the error in the log

**Comment by ozdeadmeat** [comment]
removed my JSON.lua, error still persists. the code I am trying to inject is 

`--#inject:snippetname
trigger.action.setGroupAIOn(Group.getByName("Chevy11"))
--#end`

**Comment by Dzsek** [comment]
You need to updated the DCS-Lua-Injector.lua script in your savegames/dcs/scripts/hooks directory.
This changed in the last patch
